name: Run tests

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install

      - name: Set up .env file
        run: cp .env.example .env

      - name: Generate encryption key
        run: php artisan key:generate

      - name: Run tests
        run: php vendor/bin/phpunit

